tosca_definitions_version: cloudify_dsl_1_3

imports:
  - https://cloudify.co/spec/cloudify/5.2.0/types.yaml
  - plugin:cloudify-terraform-plugin?version= >=0.15.0

inputs:
  cloud_credentials:
    type: dict
  resource_config:
    type: resource_config

data_types:
  resource_config:
    properties:
      resource_prefix:
        type: string
      bucket_name:
        type: string
      bucket_region:
        type: string

node_templates:
  terraform:
    type: cloudify.nodes.terraform
    properties:
      resource_config:
        installation_source: https://releases.hashicorp.com/terraform/0.14.3/terraform_0.14.3_linux_amd64.zip

  terraform_module:
    type: cloudify.nodes.terraform.Module
    properties:
      resource_config:
        environment_variables:
          ARM_SUBSCRIPTION_ID: { get_input: [ cloud_credentials, azure_subscription_id ] }
          ARM_TENANT_ID: { get_input: [ cloud_credentials, azure_tenant_id ] }
          ARM_CLIENT_ID: { get_input: [ cloud_credentials, azure_client_id ] }
          ARM_CLIENT_SECRET: { get_input: [ cloud_credentials, azure_client_secret ] }
        variables:
          blob_name: { get_input: [ resource_config, bucket_name ] }
          blob_rg: { concat: [{ get_input: [ resource_config, resource_prefix ]}, 'rg'] }
          blob_location: { get_input: [ resource_config, bucket_region ] }
        source:
          location: https://github.com/jrzeszutek/tf-blob/archive/master.zip
    relationships:
      - target: terraform
        type: cloudify.terraform.relationships.run_on_host

capabilities:
  bucket_url:
    value: { get_attribute: [ terraform_module, resources, blob, instances, 0, attributes, id ] }
