tosca_definitions_version: cloudify_dsl_1_3

imports:
  - https://cloudify.co/spec/cloudify/5.2.0/types.yaml
  - plugin:cloudify-terraform-plugin?version= >=0.15.0

inputs:
  resource_prefix:
    type: string
  bucket_name:
    type: string
  bucket_region:
    type: string

node_templates:
  terraform:
    type: cloudify.nodes.terraform
    properties:
      resource_config:
        installation_source: https://releases.hashicorp.com/terraform/0.14.3/terraform_0.14.3_linux_amd64.zip

  terraform_module:
    type: cloudify.nodes.terraform.Module
    properties:
      resource_config:
        environment_variables:
          ARM_SUBSCRIPTION_ID: { get_secret: azure_subscription_id }
          ARM_TENANT_ID: { get_secret: azure_tenant_id }
          ARM_CLIENT_ID: { get_secret: azure_client_id }
          ARM_CLIENT_SECRET: { get_secret: azure_client_secret }
        variables:
          blob_name: { get_input: bucket_name }
          blob_rg: { concat: [{ get_input: resource_prefix}, 'rg'] }
          blob_location: { get_input: bucket_region }
        source:
          location: https://github.com/jrzeszutek/tf-blob/archive/master.zip
    relationships:
      - target: terraform
        type: cloudify.terraform.relationships.run_on_host

capabilities:
  bucket_url:
    value: { get_attribute: [ terraform_module, resources, blob, instances, 0, attributes, id ] }
