tosca_definitions_version: cloudify_dsl_1_3

imports:
  - http://cloudify.co/spec/cloudify/5.1.0/types.yaml
  - plugin:cloudify-aws-plugin?version= >=2.5.6

dsl_definitions:
  aws_client: &aws_client
    aws_access_key_id: { get_secret: aws_access_key_id }
    aws_secret_access_key: { get_secret: aws_secret_access_key }
    region_name: { get_input: aws_region_name }

inputs:
  aws_region_name:
    type: string
  bucket_name:
    type: string
  bucket_region:
    type: string

node_templates:
  bucket:
    type: cloudify.nodes.aws.s3.Bucket
    properties:
      client_config: *aws_client
      resource_config:
        Bucket: { get_input: bucket_name }
        CreateBucketConfiguration:
          LocationConstraint: { get_input: bucket_region }

capabilities:
  bucket_url:
    value: { concat: ['https://s3.', { get_input: bucket_region }, '.amazonaws.com/', { get_input: bucket_name } ] }
