tosca_definitions_version: cloudify_dsl_1_3

imports:
  - https://cloudify.co/spec/cloudify/5.2.0/types.yaml
  - plugin:cloudify-fabric-plugin?version= >=2.0.7

node_templates:
  ttyd:
    type: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: fabric.fabric_plugin.tasks.run_script
          inputs:
            script_path: install.sh
            fabric_env: &fabric_env
              host: { get_attribute: [ ip, aws_resource_id ] }
              user: centos
              connect_kwargs:
                pkey: { get_input: [ cloud_credentials, private_key_content ] }
        configure:
          implementation: fabric.fabric_plugin.tasks.run_script
          inputs:
            script_path: configure.sh
            fabric_env: *fabric_env
        start:
          implementation: fabric.fabric_plugin.tasks.run_script
          inputs:
            script_path: start.sh
            fabric_env: *fabric_env
        stop:
          implementation: fabric.fabric_plugin.tasks.run_script
          inputs:
            script_path: stop.sh
            fabric_env: *fabric_env
        delete:
          implementation: fabric.fabric_plugin.tasks.run_script
          inputs:
            script_path: delete.sh
            fabric_env: *fabric_env
    relationships:
      - target: ip
        type: cloudify.relationships.depends_on
