tosca_definitions_version: cloudify_dsl_1_3

imports:
  - https://cloudify.co/spec/cloudify/5.2.0/types.yaml
  - plugin:cloudify-azure-plugin?version= >=3.0.9

dsl_definitions:
  azure_config: &azure_config
    subscription_id: { get_secret: azure_subscription_id }
    tenant_id: { get_secret: azure_tenant_id }
    client_id: { get_secret: azure_client_id }
    client_secret: { get_secret: azure_client_secret }

inputs:
  rg_deployment_id:
    type: string
  resource_prefix:
    type: string
  azure_location_name:
    type: string
  # availability_zones:
  #   type: list
  vm_size:
    type: string
  image:
    default:
      publisher: OpenLogic
      offer: CentOS
      sku: '7_9'
      version: '7.9.2020111900'

node_templates:
  rg_deployment:
    type: cloudify.nodes.SharedResource
    properties:
      resource_config:
        deployment:
          id: { get_input: rg_deployment_id }

  resource_group:
    type: cloudify.azure.nodes.ResourceGroup
    properties:
      use_external_resource: true
      azure_config: *azure_config
      location: { get_input: azure_location_name }
      name: { get_attribute: [ rg_deployment, capabilities, rg_id ] }
    relationships:
      - type: cloudify.relationships.depends_on
        target: rg_deployment

  subnet_1:
    type: cloudify.azure.nodes.network.Subnet
    properties:
      use_external_resource: true
      azure_config: *azure_config
      location: { get_input: azure_location_name }
      name: { get_attribute: [ rg_deployment, capabilities, subnet_ids, 0 ] }
    relationships:
      - type: cloudify.relationships.depends_on
        target: rg_deployment

  agents_security_group:
    type: cloudify.azure.nodes.network.NetworkSecurityGroup
    properties:
      use_external_resource: true
      azure_config: *azure_config
      location: { get_input: azure_location_name }
      name: { get_attribute: [ rg_deployment, capabilities, agents_security_group_id ] }
    relationships:
      - type: cloudify.relationships.depends_on
        target: rg_deployment

  vm:
    type: cloudify.azure.nodes.compute.VirtualMachine
    properties:
      azure_config: *azure_config
      name: { concat: [ { get_input: resource_prefix }, '-vm' ] }
      agent_config:
        install_method: none
      use_public_ip: true
      os_family: linux
      retry_after: 60
      location: { get_input: azure_location_name }
      # storage_endpoint: core.windows.net
      resource_config:
        hardwareProfile:
          vmSize: { get_input: vm_size }
        storageProfile:
          imageReference: { get_input: image }
        osProfile:
          linuxConfiguration:
            ssh:
              publicKeys:
              - keydata: { get_secret: aws_keypair }
                path: '/home/centos/.ssh/authorized_keys'
            disablePasswordAuthentication: true
    relationships:
      - type: cloudify.azure.relationships.contained_in_resource_group
        target: resource_group
      # - type: cloudify.azure.relationships.connected_to_storage_account
      #   target: storage_account
      # - type: cloudify.azure.relationships.connected_to_availability_set
      #   target: availability_set
      - type: cloudify.azure.relationships.connected_to_nic
        target: nic

  nic:
    type: cloudify.azure.nodes.network.NetworkInterfaceCard
    properties:
      location: { get_input: azure_location_name }
      name: { concat: [ { get_input: resource_prefix }, '-nic' ] }
      azure_config: *azure_config
      retry_after: 5
      primary: true
    relationships:
      - type: cloudify.azure.relationships.contained_in_resource_group
        target: resource_group
      - type: cloudify.azure.relationships.nic_connected_to_network_security_group
        target: agent_security_group
      - type: cloudify.azure.relationships.nic_connected_to_ip_configuration
        target: ip

  ip:
    type: cloudify.azure.nodes.network.IPConfiguration
    properties:
      location: { get_input: azure_location_name }
      name: { concat: [ { get_input: resource_prefix }, '-ip' ] }
      azure_config: *azure_config
      retry_after: 5
      resource_config:
        privateIPAllocationMethod: Dynamic
    relationships:
      - type: cloudify.azure.relationships.contained_in_resource_group
        target: resource_group
      - type: cloudify.azure.relationships.ip_configuration_connected_to_subnet
        target: subnet_1

capabilities:
  vm_ip:
    value: { get_attribute: [ ip, id ] }
