tosca_definitions_version: cloudify_dsl_1_3

imports:
  - https://cloudify.co/spec/cloudify/5.2.0/types.yaml
  - plugin:cloudify-azure-plugin?version= >=3.0.10

dsl_definitions:
  client_config: &azure_config
    subscription_id: { get_secret: azure_subscription_id }
    tenant_id: { get_secret: azure_tenant_id }
    client_id: { get_secret: azure_client_id }
    client_secret: { get_secret: azure_client_secret }

inputs:
  rg_deployment_id:
    type: string
  resource_prefix:
    type: string
  azure_location_name:
    type: string
  vm_size:
    type: string
  image:
    type: dict

labels:
  csys-obj-type:
    values:
      - environment

node_templates:
  rg_deployment:
    type: cloudify.nodes.SharedResource
    properties:
      resource_config:
        deployment:
          id: { get_input: rg_deployment_id }

  resource_group:
    type: cloudify.azure.nodes.ResourceGroup
    properties:
      use_external_resource: true
      client_config: *azure_config
      location: { get_input: azure_location_name }
      name: { get_attribute: [ rg_deployment, capabilities, rg_id ] }
    relationships:
      - type: cloudify.relationships.depends_on
        target: rg_deployment

  network:
    type: cloudify.azure.nodes.network.VirtualNetwork
    properties:
      use_external_resource: true
      client_config: *azure_config
      location: { get_input: azure_location_name }
      name: { get_attribute: [ rg_deployment, capabilities, vn_id ] }
    relationships:
      - type: cloudify.azure.relationships.contained_in_resource_group
        target: resource_group

  subnet_1:
    type: cloudify.azure.nodes.network.Subnet
    properties:
      use_external_resource: true
      client_config: *azure_config
      location: { get_input: azure_location_name }
      name: { get_attribute: [ rg_deployment, capabilities, subnet_ids, 0 ] }
    relationships:
      - type: cloudify.azure.relationships.contained_in_virtual_network
        target: network

  agents_security_group:
    type: cloudify.azure.nodes.network.NetworkSecurityGroup
    properties:
      use_external_resource: true
      client_config: *azure_config
      location: { get_input: azure_location_name }
      name: { get_attribute: [ rg_deployment, capabilities, agents_security_group_id ] }
    relationships:
      - type: cloudify.azure.relationships.contained_in_virtual_network
        target: network

  storage_account:
    type: cloudify.azure.nodes.storage.StorageAccount
    properties:
      use_external_resource: true
      client_config: *azure_config
      name: { get_attribute: [ rg_deployment, capabilities, sa_id ] }
      location: { get_input: azure_location_name }
    relationships:
      - type: cloudify.azure.relationships.contained_in_resource_group
        target: resource_group

  vm:
    type: cloudify.azure.nodes.compute.VirtualMachine
    properties:
      client_config: *azure_config
      name: { concat: [ { get_input: resource_prefix }, '-vm' ] }
      agent_config:
        install_method: none
      use_public_ip: true
      os_family: linux
      retry_after: 60
      location: { get_input: azure_location_name }
      storage_endpoint: core.windows.net
      resource_config:
        hardwareProfile:
          vmSize: { get_input: vm_size }
        storageProfile:
          imageReference: { get_input: image }
        osProfile:
          adminUsername: centos
          linuxConfiguration:
            ssh:
              publicKeys:
              - keydata: { get_secret: public_key_content }
                path: '/home/centos/.ssh/authorized_keys'
            disablePasswordAuthentication: true
    relationships:
      - type: cloudify.azure.relationships.contained_in_resource_group
        target: resource_group
      - type: cloudify.azure.relationships.connected_to_storage_account
        target: storage_account
      - type: cloudify.azure.relationships.connected_to_nic
        target: nic

  nic:
    type: cloudify.azure.nodes.network.NetworkInterfaceCard
    properties:
      location: { get_input: azure_location_name }
      name: { concat: [ { get_input: resource_prefix }, '-nic' ] }
      client_config: *azure_config
      retry_after: 5
      primary: true
    relationships:
      - type: cloudify.azure.relationships.contained_in_resource_group
        target: resource_group
      - type: cloudify.azure.relationships.nic_connected_to_network_security_group
        target: agents_security_group
      - type: cloudify.azure.relationships.nic_connected_to_ip_configuration
        target: ip

  ip:
    type: cloudify.azure.nodes.network.IPConfiguration
    properties:
      location: { get_input: azure_location_name }
      name: { concat: [ { get_input: resource_prefix }, '-ip' ] }
      client_config: *azure_config
      retry_after: 5
      resource_config:
        privateIPAllocationMethod: Dynamic
    relationships:
      - type: cloudify.azure.relationships.contained_in_resource_group
        target: resource_group
      - type: cloudify.azure.relationships.ip_configuration_connected_to_subnet
        target: subnet_1
      - type: cloudify.azure.relationships.ip_configuration_connected_to_public_ip
        target: public_ip

  public_ip:
    type: cloudify.azure.nodes.network.PublicIPAddress
    properties:
      client_config: *azure_config
      name: { concat: [ { get_input: resource_prefix }, '-public-ip' ] }
      location: { get_input: azure_location_name }
      tags:
        Name: { concat: [ { get_input: resource_prefix }, '-public-ip' ] }
      retry_after: 5
      resource_config:
        publicIPAllocationMethod: Static
    relationships:
      - type: cloudify.azure.relationships.contained_in_resource_group
        target: resource_group

capabilities:
  vm_ip:
    value: { get_attribute: [ vm, ip ] }
