kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: {{ NAME }}
spec:
  tls:
    - hosts:
        - {{ URL }}
      secretName: certbot-ssl
  rules:
    - host: {{ URL }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              serviceName: {{ SERVICE_NAME }}
              servicePort: 80
status:
  loadBalancer:
    ingress:
      - hostname: {{ HOSTNAME }}