apiVersion: v1
kind: Service
metadata:
  name: {{ NAME }}
  labels:
    app: {{ NAME }}
spec:
  ports:
    - port: 80
      nodePort: 30080
  selector:
    app: {{ NAME }}
    tier: frontend
  type: NodePort