tosca_definitions_version: cloudify_dsl_1_3

imports:
  - http://cloudify.co/spec/cloudify/5.1.0/types.yaml
  - plugin:cloudify-aws-plugin?version= >=2.5.4

dsl_definitions:
  aws_client: &aws_client
    aws_access_key_id: { get_secret: aws_access_key_id }
    aws_secret_access_key: { get_secret: aws_secret_access_key }
    region_name: { get_input: aws_region_name }

inputs:
  app_deployment_id:
    type: string
  resource_prefix:
    type: string
  aws_region_name:
    type: string
  availability_zone_1:
    type: string
  availability_zone_2:
    type: string
  ami_id:
    type: string
  instance_type:
    type: string

node_templates:
  vpc_deployment:
    type: cloudify.nodes.Component
    properties:
      resource_config:
        blueprint:
          id: vpc
          external_resource: true
        deployment:
          id: { concat: [ { get_input: app_deployment_id }, '_vpc' ] }
          inputs:
            name: { concat: [ { get_input: resource_prefix }, '-vpc' ] }
            aws_region_name: { get_input: aws_region_name }
            availability_zone_1: { get_input: availability_zone_1 }
            availability_zone_2: { get_input: availability_zone_2 }

  vpc:
    type: cloudify.nodes.aws.ec2.Vpc
    properties:
      client_config: *aws_client
      use_external_resource: true
      resource_config:
        CidrBlock: ''
      resource_id: { get_attribute: [ vpc_deployment, capabilities, vpc_id ] }
    relationships:
      - target: vpc_deployment
        type: cloudify.relationships.depends_on

  main_route_table:
    type: cloudify.nodes.aws.ec2.RouteTable
    properties:
      client_config: *aws_client
      use_external_resource: true
      resource_id: { get_attribute: [ vpc, main_route_table_id ] }
    relationships:
      - type: cloudify.relationships.contained_in
        target: vpc

  internet_gateway:
    type: cloudify.nodes.aws.ec2.InternetGateway
    properties:
      client_config: *aws_client
      use_external_resource: true
      resource_id: { get_attribute: [ vpc_deployment, capabilities, internet_gateway_id ] }
    relationships:
      - type: cloudify.relationships.connected_to
        target: vpc

  route_internet_gateway:
    type: cloudify.nodes.aws.ec2.Route
    properties:
      client_config: *aws_client
      resource_config:
        kwargs:
          DestinationCidrBlock: '0.0.0.0/0'
    relationships:
      - type: cloudify.relationships.contained_in
        target: main_route_table
      - type: cloudify.relationships.connected_to
        target: internet_gateway
    interfaces:
      cloudify.interfaces.lifecycle:
        stop: {}

  vm:
    type: cloudify.nodes.aws.ec2.Instances
    properties:
      client_config: *aws_client
      agent_config:
        install_method: none
      resource_config:
        ImageId: { get_input: ami_id }
        InstanceType: { get_input: instance_type }
        kwargs:
          KeyName: { get_secret: aws_keypair }
      Tags:
        - Key: Name
          Value: { concat: [ { get_input: resource_prefix }, '-vm' ] }
    relationships:
      - type: cloudify.relationships.depends_on
        target: ip
      - type: cloudify.relationships.depends_on
        target: nic
  ip:
    type: cloudify.nodes.aws.ec2.ElasticIP
    properties:
      client_config: *aws_client
      resource_config:
        Domain: vpc
      Tags:
        - Key: Name
          Value: { concat: [ { get_input: resource_prefix }, '-ip' ] }
    relationships:
      - type: cloudify.relationships.depends_on
        target: nic
  nic:
    type: cloudify.nodes.aws.ec2.Interface
    properties:
      client_config: *aws_client
      resource_config:
        kwargs:
          SubnetId: { get_attribute: [ vpc_deployment, capabilities, subnet_1_id ] }
          Groups:
            - { get_attribute: [ vpc_deployment, capabilities, agents_security_group_id ] }
      Tags:
        - Key: Name
          Value: { concat: [ { get_input: resource_prefix }, '-nic' ] }
    relationships:
      - target: vpc_deployment
        type: cloudify.relationships.depends_on

capabilities:
  vpc:
    description: |
      VPC information
    value: { get_attribute: [ vpc_deployment, capabilities ] }
  vm_ip:
    value: { get_attribute: [ ip, aws_resource_id ] }
