apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:stable
      volumeMounts:
      - name: volume-name
        mountPath: /usr/share/nginx/html/
  initContainers:
    - name: create-empty-file
      image: alpine
      command: ["sh", "-c", "echo Nginx > /usr/share/nginx/html/index.html"]
      volumeMounts:
      - name: volume-name
        mountPath: /usr/share/nginx/html/
  volumes:
    - name: volume-name
      emptyDir: {}
