tosca_definitions_version: cloudify_dsl_1_3

imports:
  - http://cloudify.co/spec/cloudify/5.1.0/types.yaml
  - plugin:cloudify-fabric-plugin

inputs:
  network_deployment_id:
    type: string
  master_username:
    type: string
  master_password:
    type: string

node_templates:
  database:
    type: cloudify.nodes.Root
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          implementation: fabric.fabric_plugin.tasks.run_script
          inputs:
            script_path: scripts/install-psql.sh
            fabric_env: &fabric_env
              host_string: { get_capability: [ { get_input: network_deployment_id }, vm_ip ] }
              user: centos
              key: { get_secret: private_key_content }
        configure:
          implementation: fabric.fabric_plugin.tasks.run_script
          inputs:
            script_path: scripts/configure-psql.sh
            fabric_env: *fabric_env
            master_username: { get_input: master_username }
            master_password: { get_input: master_password }
        start:
          implementation: fabric.fabric_plugin.tasks.run_script
          inputs:
            script_path: scripts/start-psql.sh
            fabric_env: *fabric_env
        stop:
          implementation: fabric.fabric_plugin.tasks.run_script
          inputs:
            script_path: scripts/stop-psql.sh
            fabric_env: *fabric_env

capabilities:
  host:
    value: { get_capability: [ { get_input: network_deployment_id }, vm_ip ] }
  master_username:
    value: { get_attribute: [ database, master_username ] }
  master_password:
    value: { get_attribute: [ database, master_password ] }
