tosca_definitions_version: cloudify_dsl_1_3

imports:
  - https://cloudify.co/spec/cloudify/5.2.0/types.yaml
  - plugin:cloudify-aws-plugin?version= >=2.5.6

dsl_definitions:
  aws_client: &aws_client
    aws_access_key_id: { get_secret: aws_access_key_id }
    aws_secret_access_key: { get_secret: aws_secret_access_key }
    region_name: { get_input: aws_region_name }

inputs:

  queue_name:
    type: string
  aws_region_name:
    type: string

node_templates:

  queue:
    type: cloudify.nodes.aws.SQS.Queue
    properties:
      client_config: *aws_client
      resource_config:
        kwargs:
          QueueName: { get_input: queue_name }

# capabilities:
#   endpoint:
#     value: { get_attribute: [ eks_cluster, kubeconf, clusters, 0, cluster, server ] }
